const cats=[['ones','에이스',d=>count(d,1)],['twos','듀스',d=>count(d,2)*2],['threes','트리플',d=>count(d,3)*3],['fours','쿼드',d=>count(d,4)*4],['fives','펜타',d=>count(d,5)*5],['sixes','헥사',d=>count(d,6)*6],['choice','초이스',d=>sum(d)],['four','포커',d=>hasN(d,4)?sum(d):0],['full','풀 하우스',d=>isFull(d)?sum(d):0],['small','스몰 스트레이트',d=>straight(d,4)?15:0],['large','라지 스트레이트',d=>straight(d,5)?30:0],['yacht','야추',d=>hasN(d,5)?50:0]];
let state={mode:'ai',turn:0,rolls:0,dice:[1,2,3,4,5],held:[false,false,false,false,false],scores:[{},{}],busy:false};
const $=s=>document.querySelector(s),count=(d,n)=>d.filter(x=>x===n).length,sum=d=>d.reduce((a,b)=>a+b,0),hasN=(d,n)=>Math.max(...[1,2,3,4,5,6].map(x=>count(d,x)))>=n;
function isFull(d){let a=[...new Set(d)].map(x=>count(d,x)).sort((a,b)=>a-b);return a.join(',')==='2,3'||a.join(',')==='1,4'}function straight(d,n){let u=[...new Set(d)].sort((a,b)=>a-b),run=1,best=1;for(let i=1;i<u.length;i++){run=u[i]===u[i-1]+1?run+1:1;best=Math.max(best,run)}return best>=n}function playerName(i){return i===0?'플레이어 1':state.mode==='ai'?'AI':'플레이어 2'}function bonus(i){return cats.slice(0,6).reduce((a,c)=>a+(state.scores[i][c[0]]??0),0)>=63?35:0}function total(i){return Object.values(state.scores[i]).reduce((a,b)=>a+b,0)+bonus(i)}
function dotPositions(n){const sets={1:[4],2:[0,8],3:[0,4,8],4:[0,2,6,8],5:[0,2,4,6,8],6:[0,2,3,5,6,8]};return [...Array(9)].map((_,i)=>`<i class="dot ${sets[n].includes(i)?'':'empty'}"></i>`).join('')}
function row(c,p){let cells=[0,1].map(i=>{let v=state.scores[i][c[0]];if(v!==undefined)return `<span class="value">${v}</span>`;if(i===p&&state.rolls&&!state.busy)return `<span class="value candidate current-player">${c[2](state.dice)}</span>`;return '<span class="value">—</span>'});return `<button class="score-row ${state.scores[p][c[0]]===undefined&&state.rolls&&!state.busy?'selectable':''}" data-cat="${c[0]}"><span class="name">${c[1]}</span>${cells.join('')}</button>`}
function render(){const p=state.turn;$('#p1-head').textContent='P1';$('#p2-head').textContent=state.mode==='ai'?'AI':'P2';$('#mode-badge').textContent=state.mode==='ai'?'VS 인공지능':'2인 플레이';$('#turn-label').innerHTML=`<b>${playerName(p)}</b>의 차례`;$('#turn-sub').textContent=state.busy?'AI가 주사위를 살피는 중…':state.rolls?`남길 주사위를 고르고, 족보를 선택하세요 · ${state.rolls}/3회 굴림`:'주사위를 굴려 게임을 시작하세요';$('#dice-area').innerHTML=state.dice.map((n,i)=>`<button class="die ${state.held[i]?'held':''} ${(!state.rolls||state.busy)?'disabled':''}" data-i="${i}" aria-label="${n}">${dotPositions(n)}</button>`).join('');$('#dice-area').querySelectorAll('.die').forEach(el=>el.onclick=()=>{if(state.rolls&&!state.busy){let i=+el.dataset.i;state.held[i]=!state.held[i];render()}});$('#roll-btn').disabled=state.rolls>=3||state.busy;$('#roll-btn').textContent=state.busy?'AI 생각 중…':state.rolls?'다시 굴리기 ('+(3-state.rolls)+'회 남음)':'주사위 굴리기';$('#hint').textContent=state.rolls?'점수판의 파란 점수 칸을 누르면 기록할 수 있습니다.':'각 주사위는 굴린 뒤 클릭하여 고정할 수 있습니다.';$('#scoreboard').innerHTML=cats.map(c=>row(c,p)).join('')+`<div class="score-row total"><span class="name">보너스</span><span class="value">${bonus(0)}</span><span class="value">${bonus(1)}</span></div><div class="score-row total"><span class="name">총점</span><span class="value">${total(0)}</span><span class="value">${total(1)}</span></div>`;document.querySelectorAll('.score-row.selectable').forEach(el=>el.onclick=()=>choose(el.dataset.cat))}
function roll(){if(state.rolls>=3||state.busy)return;state.dice=state.dice.map((x,i)=>state.held[i]?x:Math.floor(Math.random()*6)+1);state.rolls++;render()}function choose(key){if(!state.rolls||state.busy||state.scores[state.turn][key]!==undefined)return;let c=cats.find(x=>x[0]===key);state.scores[state.turn][key]=c[2](state.dice);if(Object.keys(state.scores[0]).length===12&&Object.keys(state.scores[1]).length===12){render();finish();return}state.turn=1-state.turn;state.rolls=0;state.held=[false,false,false,false,false];render();if(state.mode==='ai'&&state.turn===1)setTimeout(aiTurn,650)}function aiTurn(){state.busy=true;render();state.dice=state.dice.map(()=>Math.floor(Math.random()*6)+1);state.rolls=1;let best=cats.filter(c=>state.scores[1][c[0]]===undefined).map(c=>[c,c[2](state.dice)]).sort((a,b)=>b[1]-a[1])[0][0];setTimeout(()=>{state.busy=false;render();setTimeout(()=>choose(best[0]),500)},700)}
function finish(){let a=total(0),b=total(1),msg=a===b?'동점입니다! 멋진 승부였어요.':a>b?`${playerName(0)} 승리! ${a} : ${b}`:`${playerName(1)} 승리! ${b} : ${a}`;$('#modal-icon').textContent=a===b?'🤝':a>b?'🏆':'🎲';$('#modal-title').textContent=state.mode==='ai'?(a>b?'승리했습니다!':a===b?'무승부입니다!':'AI가 이겼습니다!'):'게임 종료';$('#modal-text').textContent=msg;$('#modal').classList.remove('hidden')}function start(mode){state={mode,turn:0,rolls:0,dice:[1,2,3,4,5],held:[false,false,false,false,false],scores:[{},{}],busy:false};$('#home').classList.add('hidden');$('#game').classList.remove('hidden');render()}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));$('#roll-btn').onclick=roll;$('#rules-toggle').onclick=()=>$('#rules').classList.toggle('hidden');$('#home-btn').onclick=()=>{$('#game').classList.add('hidden');$('#home').classList.remove('hidden')};$('#modal-btn').onclick=()=>{$('#modal').classList.add('hidden');$('#game').classList.add('hidden');$('#home').classList.remove('hidden')};
